### ISSUE TITLE
Feature and benchmark against RiotJS?

### ISSUE THREAD

**Issue by kokujin** [KingPixil/moon#36]
What are the advantages of MoonJS vs RiotJS(http://riotjs.com/)?

**Comment by KingPixil** [comment]
Moon and Riot share a lot in terms of design and API, and I feel like both have similar goals. 

* Moon is lighter, weighing in at 6kb, Riot is 9kb
* Moon is more performant in most cases. Riot traverses the DOM, while Moon generates a highly optimized virtual DOM. Since Moon has a templating engine, it can also intelligently skip over static elements, Riot cannot.
* Both frameworks have a beautiful component system ("tags" in Riot). Moon also has support for single file components via [moon-cli](https://github.com/KingPixil/moon-cli)
* Both frameworks have a router library ([moon-router](https://github.com/KingPixil/moon-router) and riot router)

It all comes down to your preferences. Which API would you prefer? Do you want a smaller bundle size and more performant library?

Let me know if you want a comparison of something else, I'm closing this for now.
