### ISSUE TITLE
ERROR: TypeError: this.count is not a function 

### ISSUE THREAD

**Issue by wilsontov** [KingPixil/moon#66]
Hey! its me again :nerd_face: 

I just want ask two things: 
## Can i run two methods with a button? 
I dont know if you understand me. I have this: 
```HTML
<button m-on:click='count' m-on:click='api(msg)'>Guardar</button>
```
But actually just the 'count' method is running. Can i run two methods?

## 2. ERROR: TypeError: this.count is not a function
I have this:
```Javascript
const app = new Moon({
    el: "#app",
    data: {
        msg: "Hola we",
        plays: 0,
        data: ''
    },
    methods: {
        count: function() {
            this.set('plays', this.get('plays') + 1);
        },
        api: function(id) {
            const url = 'https://jsonplaceholder.typicode.com';

            fetch(url + '/posts/' + id)
                .then((resp) => resp.json())
                .then(function(data) {
                    console.log(data);
                    this.count();
                }).catch(function(error) {
                    console.log("ERROR: " + error);
                });
        }
    }
});
```
When it runs everything goes well, but when it call this lines ' his.count();' i get this error: 
> ERROR: TypeError: this.count is not a function 

What could i do? Thank you!

PD: Moon is amazing. I had not wanted to learn many Javascript. I Had programmed a project in NodeJS, but really I did not like it. Having seen Moon i have remained enchanted. I am going to try it together with Rails.

**Comment by KingPixil** [comment]
First of all, thank you so much for using Moon! Super glad you like it.

You can't run two methods of the same type with `m-on`, only with different types (for example `click` and `input`).

Instead, you can make one method calling both functions.

Next, Moon doesn't proxy all of your data to `this` like Vue does, which is why you use `instance.get` and `instance.set`. To call methods, you can use [`instance.callMethod`](http://moonjs.ga/api/instance-methods.html#-callmethod-).

A working example would be:

```html
<button m-on:click='count' m-on:click='api(msg)'>Guardar</button>
```

```js
const app = new Moon({
    el: "#app",
    data: {
        msg: "Hola we",
        plays: 0,
        data: ''
    },
    methods: {
        count: function() {
            this.set('plays', this.get('plays') + 1);
        },
        api: function(id) {
            const url = 'https://jsonplaceholder.typicode.com';

            fetch(url + '/posts/' + id)
                .then((resp) => resp.json())
                .then(function(data) {
                    console.log(data);
                    this.callMethod("count");
                }).catch(function(error) {
                    console.log("ERROR: " + error);
                });
        }
    }
});
```

The reason behind using `callMethod` is that Moon has to do some extra work to get `this` reference to the instance when calling a method, so it provides it with a simpler function for you.

**Comment by wilsontov** [comment]
Thank you, Master!

**Comment by KingPixil** [comment]
No problem 😄
