### ISSUE TITLE
support for conditional and (&&)

### ISSUE THREAD

**Issue by student020341** [KingPixil/moon#72]
This directive works

`m-if="false || true"`

but this directive does not

`m-if="false && true"`

Is there a replacement character for && or is this a planned feature? Thanks!

**Comment by KingPixil** [comment]
This is because you are using the DOM as a template. If you provide a `template` option, this operator (`&&`) will work as expected.

See, the browser escapes certain characters automatically in attributes, and when it is parsing the HTML, it escapes both ampersands to `&amp`. This leads to the attribute value to be `m-if="false &amp;&amp; true"`. Moon attempts to compile this and it leads to an invalid template expression.

Here is a working example:

```html
<div id="app"></div>
```

```js
new Moon({
  el: "#app",
  template: `<div id="app">
    <h1 m-if="true && false">Not Showing</h1>
    <h1 m-if="true && true">Showing</h1>
  </div>`
});
```

[jsFiddle link](https://jsfiddle.net/kyd9xvbn/)

**Comment by student020341** [comment]
I see, thank you.

**Comment by KingPixil** [comment]
No problem.

**Comment by kbrsh** [comment]
> See, the browser escapes certain characters automatically in attributes, and when it is parsing the HTML, it escapes both ampersands to &amp;. This leads to the attribute value to be m-if="false &amp;&amp; true". Moon attempts to compile this and it leads to an invalid template expression.

Did you try the fix? Try putting the template in the `template` option rather than as a DOM element.

**Comment by Marc-oO** [comment]
Yes, your fix works like a charm, but.. my template is really huge, i can't embed it in the javascript.

**Comment by kbrsh** [comment]
There's nothing Moon can do about that, since browsers compile the HTML. In v1, Moon will compile the escape codes as normal JavaScript codes, but for any previous versions you'll have to use `template`.

Templates aren't supposed to be in the DOM _or_ in the JavaScript for production anyway. You should precompile them using either single-file components or passing `Moon.compile`'s output as the `render` option.
