### ISSUE TITLE
What is the status of moonjs

### ISSUE THREAD

**Issue by rogierverbrugge** [KingPixil/moon#87]
I am wondering what the production-level-status is of moonjs. I'm considering it for a large scale SPA. Do you have any thoughts about it yourself and would you use it in production?

**Comment by KingPixil** [comment]
First of all, thanks for considering Moon! Moon hasn't been "officially" released as production ready (it hasn't hit the `v1.0.0` mark), but it doesn't have any critical bugs either.

I have it in `v0.11.0` because I still have some features to add, and I might possibly remove things, meaning that there might still be a breaking change. Nevertheless, there will not be any significant API changes to it.

I currently use it in all of my projects and would use it in production, but I _am_ the creator of it. If you decide to use it, you might find an occasional bug here and there, and can report it here and I'll patch it. 

In the end, it's for you to decide. Are you willing to use a technology that might still have bugs? Are you able to maintain it in case of any breaking changes and feature additions? It's your choice.

**Comment by dennythecoder** [comment]
Any thoughts for providing a road map?  I'm sure there's a few folks that'd like to pitch in.

**Comment by leeoniya** [comment]
> Are you willing to use a technology that might still have bugs?

so, *all* technology? 😆

**Comment by KingPixil** [comment]
@dennythecoder I guess I could make one. It mostly includes keeping the size down and adding some sort of transition system (`m-transition`).

@leeoniya Now that I think about it, yeah :joy:

**Comment by rogierverbrugge** [comment]
Thanks for the heads up @KingPixil

**Comment by KingPixil** [comment]
No problem, thanks for considering Moon @rogierverbrugge 

Can this be closed?
